---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: sample-node-alert
spec:
  summary: ab-kind # this is very crucial without this cant tell event comes from which cluster
  providerRef:
    name: notification-sample-node
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: sample-node