---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: sample-node-alert
  namespace: ab
spec:
  summary: ab-kind
  providerRef:
    name: notification-sample-node
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: sample-node