apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-node
spec:
  interval: 1m
  chart:
    spec:
      chart: node
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: helm-sample-node
      interval: 1m
