---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-node
spec:
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: sample-node-valuse
  chart:
    spec:
      chart: node
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: noderepo
        namespace: repo
      interval: 1m