---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: notification-sample-node
spec:
  type: generic
  # webhook address (ignored if secretRef is specified)
  address: http://notif-handler.default.svc.cluster.local